Module4 task1
htmlacademy-javascript/2063947-kekstagram-27 pull request #3
Opened 2022-10-10 13:27 UTC by romanetsinna

2022-10-11 19:19 UTC, blckwltz requested changes

2022-10-11 19:19 UTC, blckwltz commented on js/main.js
> +const createDescription = (indexID, indexURL) => {
@romanetsinna тут не нужны отдельные аргументы для `id` и фото. У нас как раз 25 фото, номер будет совпадать с `id`:
```js
const createDescription = (index) => {
   // ...
   return {
     id: index + 1,
     url: `photos/${index + 1}.jpg`,
     // ...
   }
 };
```

2022-10-11 19:19 UTC, blckwltz commented on js/main.js
> +    comments: [
@romanetsinna по заданию в `comments` должен быть массив объектов определенной структуры. А сейчас получается массив разных значений

2022-10-11 19:19 UTC, blckwltz commented on js/main.js
> +const photoDescriptions = Array.from({length: 25}, (element, index) =>
@romanetsinna это как раз то самое создание массива, про которое я писал. Тут `index` будет увеличиваться на 1 (от 0) при создании каждого элемента 1 по 25. За счет этого `id` и номера фото не будет повторяться.

2022-10-11 19:19 UTC, blckwltz commented on js/main.js
> +createDescription(indexID, indexURL, indexComments));
@romanetsinna здесь нужно передавать только один аргумент (`index`)

2022-10-12 04:33 UTC, romanetsinna commented on js/main.js
> +const createDescription = (indexID, indexURL) => {
Когда я указываю `id: index + 1`, то id почему-то начинается с 0, а не с 1. Поэтому пока оставила просто `id: index
`

2022-10-12 19:55 UTC, blckwltz approved these changes

2022-10-14 18:32 UTC, merged